//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.EmpleadoArea = new HashSet<EmpleadoArea>();
            this.HorarioArea = new HashSet<HorarioArea>();
        }
    
        public int AreaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
    
        public virtual ICollection<EmpleadoArea> EmpleadoArea { get; set; }
        public virtual ICollection<HorarioArea> HorarioArea { get; set; }
    }
}
