//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.EmpleadoArea = new HashSet<EmpleadoArea>();
            this.EmpleadoPermiso = new HashSet<EmpleadoPermiso>();
        }
    
        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Edad { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
    
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual ICollection<EmpleadoArea> EmpleadoArea { get; set; }
        public virtual ICollection<EmpleadoPermiso> EmpleadoPermiso { get; set; }
    }
}
