//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.EmpleadoPermiso = new HashSet<EmpleadoPermiso>();
        }
    
        public string EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Sexo { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string NumeroSeguroSocial { get; set; }
        public string NombrePadre { get; set; }
        public string NombreMadre { get; set; }
        public string LugarNacimiento { get; set; }
        public string InformacionSensible { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Estatus { get; set; }
        public int AreaId { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual ICollection<EmpleadoPermiso> EmpleadoPermiso { get; set; }
    }
}
