//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.HorarioArea = new HashSet<HorarioArea>();
        }
    
        public int HorarioId { get; set; }
        public string Nombre { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSalida { get; set; }
        public int Estatus { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaHoraRegistro { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaHoraModificacion { get; set; }
    
        public virtual ICollection<HorarioArea> HorarioArea { get; set; }
    }
}
