//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssistanceControlEntities : DbContext
    {
        public AssistanceControlEntities()
            : base("name=AssistanceControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<Asistencia> Asistencia { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<EmpleadoPermiso> EmpleadoPermiso { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<HorarioArea> HorarioArea { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
