//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int AsistenciaId { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
