//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistance_ControlBLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssistanceControlEntities : DbContext
    {
        public AssistanceControlEntities()
            : base("name=AssistanceControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Asistencia> Asistencias { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EmpleadoArea> EmpleadoAreas { get; set; }
        public virtual DbSet<EmpleadoPermiso> EmpleadoPermisoes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<HorarioArea> HorarioAreas { get; set; }
        public virtual DbSet<Permiso> Permisoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
